In [1]:
import pandas as pd
import numpy as np

In [2]:
with open("fecondità_finale", "rb") as f:
    dataset=pd.read_csv(f)
    
dataset = dataset.sort_values(by=['Territorio', 'TIME']) # the proximity matrix is built with the prov in alphabetic order
dataset

Territorio  TIME  età.media.delle.madri.al.parto  \
930  Agrigento  2011                           30.94   
931  Agrigento  2012                           30.73   
932  Agrigento  2013                           31.09   
933  Agrigento  2014                           30.99   
934  Agrigento  2015                           31.14   
..         ...   ...                             ...   
625    Viterbo  2016                           31.99   
626    Viterbo  2017                           32.17   
627    Viterbo  2018                           32.05   
628    Viterbo  2019                           31.97   
629    Viterbo  2020                           32.38   

     età.media.dei.padri.alla.nascita.del.figlio  tasso.di.fecondità.totale  \
930                                        34.80                       1.37   
931                                        34.57                       1.35   
932                                        34.78                       1.27   
933                                        35.06                       1.33   
934                                        34.97                       1.27   
..                                           ...                        ...   
625                                        35.76                       1.23   
626                                        35.73                       1.16   
627                                        35.64                       1.20   
628                                        35.51                       1.11   
629                                        35.89                       1.09   

     tasso.di.inattività.dei.maschi  tasso.di.inattività.delle.femmine  \
930                       42.911800                          75.561168   
931                       43.934839                          74.366121   
932                       46.361107                          73.567265   
933                       47.098738                          72.427712   
934                       45.169256                          75.916130   
..                              ...                                ...   
625                       39.518267                          60.635768   
626                       41.158020                          61.241767   
627                       42.945825                          61.820030   
628                       44.935350                          63.118101   
629                       44.905846                          64.382497   

     tasso.di.inattività.totale  tasso.di.occupazione.dei.maschi  \
930                   59.924924                        47.392418   
931                   59.780301                        45.282895   
932                   60.518499                        43.469198   
933                   60.272133                        39.673492   
934                   61.148536                        40.057236   
..                          ...                              ...   
625                   50.408778                        52.769263   
626                   51.511845                        51.680541   
627                   52.659989                        50.508888   
628                   54.287825                        49.777042   
629                   54.909631                        50.891552   

     tasso.di.occupazione.delle.femmine  tasso.di.occupazione.totale  
930                           19.828757                    33.029603  
931                           20.513632                    32.385627  
932                           19.889053                    31.198656  
933                           20.296449                    29.595648  
934                           18.153835                    28.674135  
..                                  ...                          ...  
625                           32.263986                    42.194134  
626                           33.283508                    42.195912  
627                           33.4588

In [4]:
Y=np.array(dataset["tasso.di.fecondità.totale"])

print(np.var(Y))
print(np.mean(Y))


y = []
y_tmp = np.zeros(10)
for prov in np.unique(dataset["Territorio"]):
    data_prov = dataset[dataset["Territorio"] == prov]
    y_tmp = np.array(data_prov["tasso.di.fecondità.totale"])
    y_tmp = (y_tmp - np.mean(y_tmp))/np.sqrt(np.var(y_tmp)) #if you want to stand the answer
    y.append(y_tmp)
y = np.array(y)
print(y)
print(y.shape)


0.015125712353150588
1.3187169811320756
[[ 1.86310328  1.37281295 -0.58834841 ... -0.09805807 -1.32378391
  -0.83349357]
 [ 1.3764944   1.23310957  0.37280057 ... -0.7742781  -1.49120227
  -1.77797194]
 [ 1.44853442  1.32577726  0.46647719 ... -1.00660866 -1.37488013
  -1.37488013]
 ...
 [-0.15041421  2.25621314 -1.35372788 ...  0.15041421 -1.05289947
   0.45124263]
 [ 1.25685463  1.55971117  0.65114155 ... -0.56028459 -1.46885421
  -1.31742594]
 [ 1.33591282  1.33591282  0.22265214 ... -0.19482062 -1.44723888
  -1.72555405]]
(106, 10)


In [5]:
X1=np.array(dataset["età.media.delle.madri.al.parto"])
X2=np.array(dataset["tasso.di.occupazione.delle.femmine"])
X3=np.array(dataset["tasso.di.inattività.delle.femmine"])
X4=np.array(dataset["tasso.di.occupazione.totale"])
X5=np.array(dataset["tasso.di.inattività.totale"])

In [10]:
P = 5
X=np.ones((1060,P))

X1 = (X1 - np.mean(X1))/np.sqrt(np.var(X1))  #if u want to standardize the first cov 
X[:,0]=X1
X2 = (X2 - np.mean(X2))/np.sqrt(np.var(X2))  #if u want to standardize the sec cov
X[:,1]=X2
X3 = (X3 - np.mean(X3))/np.sqrt(np.var(X3)) #if u want to standardize the third cov 
X[:,2]=X3
X4 = (X4 - np.mean(X4))/np.sqrt(np.var(X4)) #if u want to standardize the fourth cov 
X[:,3]=X4
X5 = (X5 - np.mean(X5))/np.sqrt(np.var(X5)) #if u want to standardize the 5 cov
X[:,4]=X5


X_r = np.reshape(X,(106,10,P))
print(X_r)

[[[-1.38733389 -1.81625192  2.05144371 -1.44190544  1.51189504]
  [-1.77061906 -1.7347706   1.89211824 -1.52978636  1.48684343]
  [-1.11355877 -1.80907835  1.78561354 -1.69176769  1.61471414]
  ...
  [-0.18272337 -2.07454665  1.69594042 -1.85472312  1.27386138]
  [-0.29223342 -1.76815191  1.66432349 -1.69948922  1.39528294]
  [-0.03670997 -1.84282015  1.78846129 -1.81347883  1.75639932]]

 [[-1.64285734  0.51836657 -0.34660173  0.364978   -0.13154615]
  [-1.27782385  0.60314497 -0.71508174  0.4052295  -0.55014197]
  [-0.73027361  0.15451856 -0.41062779  0.10920909 -0.25695713]
  ...
  [-0.20097504  0.46379505 -0.48714728  0.35620227 -0.44236774]
  [ 0.03629673  0.27341734 -0.3382982   0.3386616  -0.33345926]
  [ 0.10930342  0.17544987 -0.19435256  0.1233927  -0.06778332]]

 [[-0.82153198  0.82145054 -0.82850129  0.63377123 -0.51334466]
  [-0.60251189  0.65789708 -0.80411705  0.67575927 -0.80406753]
  [-0.43824681  0.6845386  -0.94808962  0.55060687 -0.84228611]
  ...
  [ 1.02188716  0.

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
models = []
for i in range(106):
    models.append(LinearRegression().fit(X_r[i], y[i]))


In [14]:
#calcolo betaols for each province
betaols = []
for j in range(106):
    beta = np.zeros(P+1)
    beta[0] = models[j].intercept_
    for i in range(1,P+1):
        beta[i] = models[j].coef_[i-1]
    betaols.append(beta)

betaols = np.array(betaols)
print(betaols)   
betaols.shape

[[ 2.72582532e+00 -1.19071711e+00 -2.65241271e-01  1.28328688e-01
   1.43272546e+00 -1.21715512e+00]
 [-2.14955310e+00 -1.36756753e+00 -1.66013588e+00 -4.86969892e+00
   1.75335112e+00  2.35614957e+00]
 [-1.03517744e+00 -1.30263798e+00 -5.76089195e+00 -4.90683851e+00
   6.25572091e+00  3.49456925e+00]
 [-1.41387203e+00 -1.83910637e+00 -2.02456447e+00 -3.92834377e+00
   5.88276096e+00  4.75943954e+00]
 [ 2.20686128e+00 -1.52788108e+00  4.96531305e+00  4.40588825e+00
  -3.65317196e+00 -3.70083002e+00]
 [-1.14980414e+00 -1.56517566e+00 -2.86092762e+00 -7.75439229e+00
  -1.74005490e+00  3.09764370e+00]
 [-1.63577390e+00  5.84603947e-01 -1.17510356e+00  5.55848804e+00
   2.30268169e+00 -3.60972288e+00]
 [ 7.61972431e+00 -3.09591015e+00  1.68834348e+01  4.37187134e+00
  -9.74843221e+00 -1.83312343e+00]
 [ 9.31295480e+00 -2.35594036e+00 -2.24020602e+01 -1.77125093e+01
   1.97072329e+01  7.77846044e+00]
 [-1.31190385e-01 -9.76270048e-01 -8.60375181e+00  3.64049015e+00
   1.13310152e+01 -2.6138

(106, 6)

In [69]:
# estimate of sigma for each model
sigma_hat = np.zeros(106)
for i in range(106):
    sigma_hat[i] = np.sum((models[i].predict(X_r[i]) - y[i])**2)

sigma_hat = sigma_hat/(10 - (P + 1)) #da capire quanto valgono i degree of freedom 
sigma_hat = np.sqrt(sigma_hat) 
print(sigma_hat)

[0.9155067  0.49249579 0.27316686 0.93651179 0.40472942 0.83563369
 0.90010969 0.73200853 0.75899406 0.46328499 1.06913567 0.45478557
 0.42616371 0.4002463  0.12142396 0.27425427 0.85603271 0.66568824
 0.65792976 0.50382264 0.32719019 0.80106238 0.32151175 0.5039647
 1.35812021 0.38558537 1.15436993 0.41602704 0.69458209 0.53161973
 0.7917079  0.25240359 0.4383828  0.38831307 0.6928664  0.3317304
 0.75765232 1.01579134 0.89907665 1.24055946 0.32269562 1.15920556
 0.53984648 0.43711001 0.55126095 0.83958665 0.41465831 0.50096871
 0.35743523 0.25740017 0.41899559 0.8486803  0.68750852 0.2054177
 0.30135845 0.45902636 0.16872362 0.51803528 0.41942855 0.9065489
 0.14051032 0.64079907 0.24459008 0.253236   0.13343691 0.25922762
 0.56358084 0.95620642 0.26413135 0.3485779  0.34356329 1.37593309
 0.40785508 1.01938736 0.29839174 0.64831811 0.26143014 0.81675174
 0.29210092 0.43430871 0.16846575 0.24515539 0.71149669 0.6135827
 0.50114538 0.34288848 0.29226722 0.86167494 0.45946404 0.61823944


In [74]:
# estimate of variance of beta
var = []
for i in range(106):
    var.append(sigma_hat[i]*sigma_hat[i]*(np.linalg.inv(np.matmul(np.transpose(X_r[i]),X_r[i]))))
var = np.array(var)
print(var[1])

[[ 0.12871111  0.05834458 -0.62034697 -0.1763142   0.45246536]
 [ 0.05834458  7.15098284  3.80887744 -7.18666316 -2.9369999 ]
 [-0.62034697  3.80887744  9.9160798  -1.25300196 -8.01519228]
 [-0.1763142  -7.18666316 -1.25300196  9.89520539  1.91229718]
 [ 0.45246536 -2.9369999  -8.01519228  1.91229718  7.43337986]]
